import { BaseCheck } from "./base.js";
import type {
  CheckConfig,
  CheckResult,
  RepoContext,
  CommitInfo,
  CommitDetail,
  GitForensicsData,
} from "../core/types.js";
import type { ClaudeClient } from "../ai/claude.js";

// ── Constants ───────────────────────────────────────────────

/** Commit messages that suggest low effort or auto-generation */
const GENERIC_MESSAGES = [
  "initial commit",
  "first commit",
  "init",
  "update",
  "fix",
  "wip",
  "asdf",
  "test",
  "stuff",
  "changes",
  ".",
  "...",
  "commit",
  "save",
  "temp",
  "tmp",
  "misc",
  "no message",
  "untitled",
  "a",
  "aa",
  "aaa",
];

/** Messages that hint at code being imported/copied from elsewhere */
const COPY_INDICATORS = [
  "initial import",
  "migrate from",
  "copy from",
  "copied from",
  "moved from",
  "imported from",
  "ported from",
  "forked from",
  "cloned from",
  "transfer from",
  "migrated from",
  "upload project",
  "upload files",
  "add files via upload",
];

/** Auto-generated message patterns */
const AUTO_GEN_PATTERNS = [
  /^merge pull request/i,
  /^merge branch/i,
  /^auto-generated/i,
  /^generated by/i,
  /^create \S+\.\S+$/i, // "Create README.md" - GitHub web editor
  /^update \S+\.\S+$/i, // "Update index.js" - GitHub web editor
  /^delete \S+\.\S+$/i,
  /^rename \S+ to \S+$/i,
  /^add files via upload$/i,
  /^initial commit$/i,
];

// ── Interfaces ──────────────────────────────────────────────

interface ForensicsAnalysis {
  commitPatterns: {
    totalCommits: number;
    uniqueDays: number;
    spanDays: number;
    avgTimeBetweenCommitsHours: number;
    longestGapDays: number;
    shortestGapMinutes: number;
    commitsInFirstDay: number;
    commitsInLastDay: number;
    singleSessionCommits: boolean; // all within 1 hour
    bulkCommitCount: number; // commits with >500 lines added
  };
  messageQuality: {
    genericCount: number;
    meaningfulCount: number;
    autoGeneratedCount: number;
    copyIndicatorCount: number;
    averageLength: number;
    genericRatio: number;
  };
  codeChurn: {
    totalAdditions: number;
    totalDeletions: number;
    addDeleteRatio: number;
    largestSingleCommitLines: number;
    largestCommitPercentage: number; // % of total code in one commit
    averageCommitSize: number;
  };
  contributors: {
    totalContributors: number;
    primaryAuthor: string;
    primaryAuthorCommitPercentage: number;
    uniqueAuthorEmails: string[];
    authorMatchesOwner: boolean;
  };
  timeline: {
    repoAgeDays: number;
    developmentSpanDays: number;
    lastPushDaysAgo: number;
    createdAndCompletedSameDay: boolean;
    dormantThenBurst: boolean;
    velocityCommitsPerWeek: number;
  };
  redFlags: string[];
  greenFlags: string[];
  riskScore: number; // 0-100, higher = more suspicious
}

interface AIForensicsAnalysis {
  verdict: "genuine" | "suspicious" | "likely_copied";
  confidence: number;
  reason: string;
  details: string[];
  recommendations: string[];
}

// ── Check Implementation ────────────────────────────────────

export class GitForensicsCheck extends BaseCheck {
  id = "git_forensics";
  name = "Git History Forensics";
  description =
    "Analyzes commit patterns, code churn, and development timeline to verify genuine development effort.";

  private claude?: ClaudeClient;

  constructor(claude?: ClaudeClient) {
    super();
    this.claude = claude;
  }

  async run(context: RepoContext, config: CheckConfig): Promise<CheckResult> {
    if (!context.forensics) {
      return this.skip(
        "Git forensics data not available (GitHub API data not loaded)",
        config
      );
    }

    const forensics = context.forensics;

    try {
      const analysis = this.analyzeForensics(forensics, context);

      // Try AI-enhanced analysis if available
      if (this.claude) {
        return await this.aiEnhancedResult(analysis, forensics, context, config);
      }

      return this.heuristicResult(analysis, config);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return this.error(`Git forensics analysis failed: ${message}`, config);
    }
  }

  // ── Core Analysis ───────────────────────────────────────

  private analyzeForensics(
    data: GitForensicsData,
    context: RepoContext
  ): ForensicsAnalysis {
    const commits = data.commits;
    const details = data.commitDetails;
    const contributors = data.contributors;
    const metadata = data.metadata;

    const commitPatterns = this.analyzeCommitPatterns(commits);
    const messageQuality = this.analyzeMessageQuality(commits);
    const codeChurn = this.analyzeCodeChurn(details, commits.length);
    const contributorAnalysis = this.analyzeContributors(
      commits,
      contributors,
      context.owner
    );
    const timeline = this.analyzeTimeline(commits, metadata);

    const redFlags: string[] = [];
    const greenFlags: string[] = [];

    // ── Red Flag Detection ──────────────────────────────

    // Single commit with entire project
    if (commits.length === 1) {
      redFlags.push(
        "Repository has only a single commit - entire project added at once"
      );
    }

    // All commits within 1 hour
    if (commitPatterns.singleSessionCommits && commits.length > 1) {
      redFlags.push(
        `All ${commits.length} commits occurred within a single 1-hour session`
      );
    }

    // Bulk commits (massive single additions)
    if (commitPatterns.bulkCommitCount > 0) {
      redFlags.push(
        `${commitPatterns.bulkCommitCount} bulk commit(s) adding >500 lines each`
      );
    }

    // Largest commit is most of the codebase
    if (codeChurn.largestCommitPercentage > 80 && commits.length > 1) {
      redFlags.push(
        `Single commit contains ${Math.round(codeChurn.largestCommitPercentage)}% of all code - suggests copy-paste`
      );
    }

    // Copy indicator messages
    if (messageQuality.copyIndicatorCount > 0) {
      redFlags.push(
        `${messageQuality.copyIndicatorCount} commit message(s) suggest code was copied or imported`
      );
    }

    // Very high generic message ratio
    if (messageQuality.genericRatio > 0.7 && commits.length > 3) {
      redFlags.push(
        `${Math.round(messageQuality.genericRatio * 100)}% of commit messages are generic/low-effort`
      );
    }

    // Author doesn't match repo owner
    if (!contributorAnalysis.authorMatchesOwner) {
      redFlags.push(
        `Primary commit author (${contributorAnalysis.primaryAuthor}) doesn't match repo owner (${context.owner})`
      );
    }

    // Created and completed same day for complex project
    if (
      timeline.createdAndCompletedSameDay &&
      context.tree.filter((e) => e.type === "blob").length > 20
    ) {
      redFlags.push(
        "Repository created and completed in the same day despite having 20+ files"
      );
    }

    // Dormant then burst
    if (timeline.dormantThenBurst) {
      redFlags.push(
        "Repository was dormant for an extended period then had a sudden burst of activity"
      );
    }

    // Very old repo with recent activity (repurposed)
    if (timeline.repoAgeDays > 365 && timeline.developmentSpanDays < 7) {
      redFlags.push(
        `Repo is ${Math.round(timeline.repoAgeDays / 30)} months old but all development happened in ${timeline.developmentSpanDays} day(s) - possibly repurposed`
      );
    }

    // Fork detection
    if (metadata.isFork) {
      redFlags.push(
        `Repository is a fork of ${metadata.parentFullName || "another project"}`
      );
    }

    // High star/fork count (pre-existing popular project)
    if (metadata.stargazersCount > 50) {
      redFlags.push(
        `Repository has ${metadata.stargazersCount} stars - may be a pre-existing popular project`
      );
    }

    // No deletions at all (only additions = likely dump, not iterative dev)
    if (
      codeChurn.totalDeletions === 0 &&
      codeChurn.totalAdditions > 500 &&
      commits.length > 1
    ) {
      redFlags.push(
        "No code deletions across any commits - no iterative refinement detected"
      );
    }

    // All commits by auto-gen patterns (GitHub web editor only)
    if (
      messageQuality.autoGeneratedCount === commits.length &&
      commits.length > 2
    ) {
      redFlags.push(
        "All commits appear to be auto-generated (e.g., GitHub web editor)"
      );
    }

    // ── Green Flag Detection ────────────────────────────

    // Good commit spread
    if (commitPatterns.uniqueDays >= 3 && commitPatterns.spanDays >= 3) {
      greenFlags.push(
        `Development spread across ${commitPatterns.uniqueDays} different days over ${commitPatterns.spanDays} days`
      );
    }

    // Meaningful commit messages
    if (messageQuality.genericRatio < 0.3 && commits.length > 3) {
      greenFlags.push(
        `${Math.round((1 - messageQuality.genericRatio) * 100)}% of commit messages are meaningful and descriptive`
      );
    }

    // Healthy add/delete ratio
    if (
      codeChurn.addDeleteRatio > 0.1 &&
      codeChurn.addDeleteRatio < 10 &&
      codeChurn.totalDeletions > 0
    ) {
      greenFlags.push(
        "Healthy code churn ratio - shows iterative refinement (adding and deleting code)"
      );
    }

    // Small iterative commits
    if (codeChurn.averageCommitSize < 200 && commits.length > 5) {
      greenFlags.push(
        `Small iterative commits averaging ${Math.round(codeChurn.averageCommitSize)} lines - indicates steady development`
      );
    }

    // Consistent development over time
    if (timeline.velocityCommitsPerWeek >= 2 && timeline.developmentSpanDays >= 7) {
      greenFlags.push(
        `Steady development velocity: ~${timeline.velocityCommitsPerWeek.toFixed(1)} commits/week over ${timeline.developmentSpanDays} days`
      );
    }

    // Multiple contributors (for a student project, this is neutral/positive)
    if (contributorAnalysis.totalContributors >= 2) {
      greenFlags.push(
        `${contributorAnalysis.totalContributors} contributors participated`
      );
    }

    // ── Risk Score Calculation ──────────────────────────

    const riskScore = this.calculateRiskScore(
      commitPatterns,
      messageQuality,
      codeChurn,
      contributorAnalysis,
      timeline,
      metadata,
      commits.length,
      context.tree.filter((e) => e.type === "blob").length
    );

    return {
      commitPatterns,
      messageQuality,
      codeChurn,
      contributors: contributorAnalysis,
      timeline,
      redFlags,
      greenFlags,
      riskScore,
    };
  }

  // ── Commit Pattern Analysis ───────────────────────────

  private analyzeCommitPatterns(commits: CommitInfo[]) {
    if (commits.length === 0) {
      return {
        totalCommits: 0,
        uniqueDays: 0,
        spanDays: 0,
        avgTimeBetweenCommitsHours: 0,
        longestGapDays: 0,
        shortestGapMinutes: 0,
        commitsInFirstDay: 0,
        commitsInLastDay: 0,
        singleSessionCommits: true,
        bulkCommitCount: 0,
      };
    }

    const dates = commits
      .map((c) => new Date(c.date).getTime())
      .sort((a, b) => a - b);

    const uniqueDays = new Set(
      dates.map((d) => new Date(d).toISOString().slice(0, 10))
    ).size;

    const firstDate = dates[0];
    const lastDate = dates[dates.length - 1];
    const spanMs = lastDate - firstDate;
    const spanDays = Math.max(1, Math.ceil(spanMs / (1000 * 60 * 60 * 24)));

    // Gaps between commits
    const gaps: number[] = [];
    for (let i = 1; i < dates.length; i++) {
      gaps.push(dates[i] - dates[i - 1]);
    }

    const avgGapMs = gaps.length > 0 ? gaps.reduce((a, b) => a + b, 0) / gaps.length : 0;
    const avgTimeBetweenCommitsHours = avgGapMs / (1000 * 60 * 60);
    const longestGapDays =
      gaps.length > 0
        ? Math.max(...gaps) / (1000 * 60 * 60 * 24)
        : 0;
    const shortestGapMinutes =
      gaps.length > 0
        ? Math.min(...gaps) / (1000 * 60)
        : 0;

    // All within 1 hour?
    const singleSessionCommits = spanMs <= 60 * 60 * 1000;

    // First/last day commit counts
    const firstDayStr = new Date(firstDate).toISOString().slice(0, 10);
    const lastDayStr = new Date(lastDate).toISOString().slice(0, 10);
    const commitsInFirstDay = commits.filter(
      (c) => new Date(c.date).toISOString().slice(0, 10) === firstDayStr
    ).length;
    const commitsInLastDay = commits.filter(
      (c) => new Date(c.date).toISOString().slice(0, 10) === lastDayStr
    ).length;

    return {
      totalCommits: commits.length,
      uniqueDays,
      spanDays,
      avgTimeBetweenCommitsHours: Math.round(avgTimeBetweenCommitsHours * 10) / 10,
      longestGapDays: Math.round(longestGapDays * 10) / 10,
      shortestGapMinutes: Math.round(shortestGapMinutes * 10) / 10,
      commitsInFirstDay,
      commitsInLastDay,
      singleSessionCommits,
      bulkCommitCount: 0, // will be set from code churn
    };
  }

  // ── Message Quality Analysis ──────────────────────────

  private analyzeMessageQuality(commits: CommitInfo[]) {
    if (commits.length === 0) {
      return {
        genericCount: 0,
        meaningfulCount: 0,
        autoGeneratedCount: 0,
        copyIndicatorCount: 0,
        averageLength: 0,
        genericRatio: 0,
      };
    }

    let genericCount = 0;
    let autoGeneratedCount = 0;
    let copyIndicatorCount = 0;
    let totalLength = 0;

    for (const commit of commits) {
      const msg = commit.message.split("\n")[0].trim().toLowerCase();
      totalLength += msg.length;

      // Check generic
      if (
        GENERIC_MESSAGES.includes(msg) ||
        msg.length <= 2
      ) {
        genericCount++;
      }

      // Check auto-generated
      if (AUTO_GEN_PATTERNS.some((p) => p.test(msg))) {
        autoGeneratedCount++;
      }

      // Check copy indicators
      if (
        COPY_INDICATORS.some((indicator) => msg.includes(indicator))
      ) {
        copyIndicatorCount++;
      }
    }

    const meaningfulCount = commits.length - genericCount - autoGeneratedCount;

    return {
      genericCount,
      meaningfulCount: Math.max(0, meaningfulCount),
      autoGeneratedCount,
      copyIndicatorCount,
      averageLength: Math.round(totalLength / commits.length),
      genericRatio: (genericCount + autoGeneratedCount) / commits.length,
    };
  }

  // ── Code Churn Analysis ───────────────────────────────

  private analyzeCodeChurn(details: CommitDetail[], totalCommitCount: number) {
    if (details.length === 0) {
      return {
        totalAdditions: 0,
        totalDeletions: 0,
        addDeleteRatio: 0,
        largestSingleCommitLines: 0,
        largestCommitPercentage: 0,
        averageCommitSize: 0,
      };
    }

    let totalAdditions = 0;
    let totalDeletions = 0;
    let largestSingleCommitLines = 0;

    for (const detail of details) {
      totalAdditions += detail.stats.additions;
      totalDeletions += detail.stats.deletions;
      const commitTotal = detail.stats.additions + detail.stats.deletions;
      if (commitTotal > largestSingleCommitLines) {
        largestSingleCommitLines = commitTotal;
      }
    }

    const totalChanges = totalAdditions + totalDeletions;
    const addDeleteRatio =
      totalDeletions > 0 ? totalAdditions / totalDeletions : totalAdditions > 0 ? Infinity : 0;
    const largestCommitPercentage =
      totalAdditions > 0
        ? (largestSingleCommitLines / totalChanges) * 100
        : 0;

    return {
      totalAdditions,
      totalDeletions,
      addDeleteRatio: Math.round(addDeleteRatio * 100) / 100,
      largestSingleCommitLines,
      largestCommitPercentage: Math.round(largestCommitPercentage * 10) / 10,
      averageCommitSize: Math.round(totalChanges / Math.max(1, totalCommitCount)),
    };
  }

  // ── Contributor Analysis ──────────────────────────────

  private analyzeContributors(
    commits: CommitInfo[],
    contributors: { login: string; contributions: number }[],
    repoOwner: string
  ) {
    const emailCounts = new Map<string, number>();
    const nameCounts = new Map<string, number>();

    for (const commit of commits) {
      emailCounts.set(
        commit.authorEmail,
        (emailCounts.get(commit.authorEmail) || 0) + 1
      );
      nameCounts.set(
        commit.authorName,
        (nameCounts.get(commit.authorName) || 0) + 1
      );
    }

    const uniqueEmails = [...emailCounts.keys()];
    const primaryEntry = [...emailCounts.entries()].sort(
      (a, b) => b[1] - a[1]
    )[0];
    const primaryAuthor = primaryEntry ? primaryEntry[0] : "unknown";
    const primaryAuthorCount = primaryEntry ? primaryEntry[1] : 0;
    const primaryAuthorCommitPercentage =
      commits.length > 0 ? (primaryAuthorCount / commits.length) * 100 : 0;

    // Check if author matches owner (by login or name)
    const ownerLower = repoOwner.toLowerCase();
    const authorMatchesOwner =
      commits.some(
        (c) => c.authorLogin?.toLowerCase() === ownerLower
      ) ||
      [...nameCounts.keys()].some(
        (name) => name.toLowerCase().includes(ownerLower) || ownerLower.includes(name.toLowerCase())
      );

    return {
      totalContributors: Math.max(contributors.length, uniqueEmails.length),
      primaryAuthor,
      primaryAuthorCommitPercentage:
        Math.round(primaryAuthorCommitPercentage * 10) / 10,
      uniqueAuthorEmails: uniqueEmails,
      authorMatchesOwner,
    };
  }

  // ── Timeline Analysis ─────────────────────────────────

  private analyzeTimeline(
    commits: CommitInfo[],
    metadata: {
      createdAt: string;
      pushedAt: string;
    }
  ) {
    const now = new Date();
    const createdAt = new Date(metadata.createdAt);
    const pushedAt = new Date(metadata.pushedAt);
    const repoAgeDays = Math.ceil(
      (now.getTime() - createdAt.getTime()) / (1000 * 60 * 60 * 24)
    );
    const lastPushDaysAgo = Math.ceil(
      (now.getTime() - pushedAt.getTime()) / (1000 * 60 * 60 * 24)
    );

    if (commits.length === 0) {
      return {
        repoAgeDays,
        developmentSpanDays: 0,
        lastPushDaysAgo,
        createdAndCompletedSameDay: false,
        dormantThenBurst: false,
        velocityCommitsPerWeek: 0,
      };
    }

    const dates = commits
      .map((c) => new Date(c.date).getTime())
      .sort((a, b) => a - b);
    const firstCommit = dates[0];
    const lastCommit = dates[dates.length - 1];
    const devSpanMs = lastCommit - firstCommit;
    const developmentSpanDays = Math.max(
      1,
      Math.ceil(devSpanMs / (1000 * 60 * 60 * 24))
    );

    const createdAndCompletedSameDay =
      createdAt.toISOString().slice(0, 10) ===
      new Date(lastCommit).toISOString().slice(0, 10);

    // Detect dormant then burst: check if >75% of commits are in the last 25% of the repo's life
    let dormantThenBurst = false;
    if (repoAgeDays > 30 && commits.length > 3) {
      const repoLifespan = now.getTime() - createdAt.getTime();
      const last25pctStart = createdAt.getTime() + repoLifespan * 0.75;
      const commitsInLast25pct = dates.filter((d) => d >= last25pctStart).length;
      dormantThenBurst =
        commitsInLast25pct / commits.length > 0.75;
    }

    const devWeeks = Math.max(1, developmentSpanDays / 7);
    const velocityCommitsPerWeek = commits.length / devWeeks;

    return {
      repoAgeDays,
      developmentSpanDays,
      lastPushDaysAgo,
      createdAndCompletedSameDay,
      dormantThenBurst,
      velocityCommitsPerWeek:
        Math.round(velocityCommitsPerWeek * 10) / 10,
    };
  }

  // ── Risk Score Calculation ────────────────────────────

  private calculateRiskScore(
    commitPatterns: ForensicsAnalysis["commitPatterns"],
    messageQuality: ForensicsAnalysis["messageQuality"],
    codeChurn: ForensicsAnalysis["codeChurn"],
    contributors: ForensicsAnalysis["contributors"],
    timeline: ForensicsAnalysis["timeline"],
    metadata: { isFork: boolean; stargazersCount: number },
    commitCount: number,
    fileCount: number
  ): number {
    let risk = 0;

    // Single commit = very high risk
    if (commitCount === 1) risk += 30;
    // Very few commits for many files
    else if (commitCount <= 3 && fileCount > 20) risk += 20;

    // All commits in one session
    if (commitPatterns.singleSessionCommits && commitCount > 1) risk += 25;

    // One commit has most of the code
    if (codeChurn.largestCommitPercentage > 80 && commitCount > 1) risk += 20;
    else if (codeChurn.largestCommitPercentage > 60 && commitCount > 1) risk += 10;

    // High generic message ratio
    if (messageQuality.genericRatio > 0.7) risk += 10;

    // Copy indicator messages
    if (messageQuality.copyIndicatorCount > 0) risk += 15;

    // Author doesn't match owner
    if (!contributors.authorMatchesOwner) risk += 10;

    // Fork
    if (metadata.isFork) risk += 15;

    // High stars (pre-existing project)
    if (metadata.stargazersCount > 50) risk += 15;
    else if (metadata.stargazersCount > 10) risk += 5;

    // Created and completed same day with many files
    if (timeline.createdAndCompletedSameDay && fileCount > 20) risk += 15;

    // Dormant then burst
    if (timeline.dormantThenBurst) risk += 10;

    // No deletions (pure dump)
    if (codeChurn.totalDeletions === 0 && codeChurn.totalAdditions > 500) risk += 10;

    // ── Risk Reduction (green signals) ──

    // Good commit spread
    if (commitPatterns.uniqueDays >= 5) risk -= 10;
    else if (commitPatterns.uniqueDays >= 3) risk -= 5;

    // Meaningful messages
    if (messageQuality.genericRatio < 0.3 && commitCount > 3) risk -= 5;

    // Healthy churn
    if (
      codeChurn.addDeleteRatio > 0.1 &&
      codeChurn.addDeleteRatio < 10 &&
      codeChurn.totalDeletions > 0
    )
      risk -= 5;

    // Small iterative commits
    if (codeChurn.averageCommitSize < 200 && commitCount > 5) risk -= 5;

    return Math.max(0, Math.min(100, risk));
  }

  // ── Heuristic Result (no AI) ──────────────────────────

  private heuristicResult(
    analysis: ForensicsAnalysis,
    config: CheckConfig
  ): CheckResult {
    const evidence = [
      ...analysis.redFlags.map((f) => `RED FLAG: ${f}`),
      ...analysis.greenFlags.map((f) => `OK: ${f}`),
      `Commits: ${analysis.commitPatterns.totalCommits} over ${analysis.commitPatterns.spanDays} day(s)`,
      `Development spread: ${analysis.commitPatterns.uniqueDays} unique days`,
      `Message quality: ${analysis.messageQuality.meaningfulCount} meaningful, ${analysis.messageQuality.genericCount} generic`,
      `Code churn: +${analysis.codeChurn.totalAdditions} / -${analysis.codeChurn.totalDeletions} lines`,
      `Risk score: ${analysis.riskScore}/100`,
    ];

    if (analysis.riskScore >= 60) {
      return {
        checkName: this.id,
        required: config.required,
        status: config.severity === "warning" ? "warning" : "fail",
        confidence: 0.7,
        evidence,
        reason: `High risk of non-genuine development (risk score: ${analysis.riskScore}/100). ${analysis.redFlags.length} red flag(s) detected.`,
        aiUsed: false,
      };
    }

    if (analysis.riskScore >= 30) {
      return {
        checkName: this.id,
        required: config.required ?? false,
        status: "warning",
        confidence: 0.6,
        evidence,
        reason: `Moderate risk indicators detected (risk score: ${analysis.riskScore}/100). ${analysis.redFlags.length} red flag(s) found but some positive signals present.`,
        aiUsed: false,
      };
    }

    return {
      checkName: this.id,
      required: config.required,
      status: "pass",
      confidence: 0.8,
      evidence,
      reason: `Development history appears genuine (risk score: ${analysis.riskScore}/100). ${analysis.greenFlags.length} positive indicator(s) found.`,
      aiUsed: false,
    };
  }

  // ── AI-Enhanced Result ────────────────────────────────

  private async aiEnhancedResult(
    analysis: ForensicsAnalysis,
    data: GitForensicsData,
    context: RepoContext,
    config: CheckConfig
  ): Promise<CheckResult> {
    try {
      // Build a summary for Claude to analyze
      const commitSample = data.commits.slice(0, 30).map((c) => ({
        date: c.date,
        message: c.message.split("\n")[0].slice(0, 100),
        author: c.authorName,
      }));

      const detailSample = data.commitDetails.slice(0, 10).map((d) => ({
        sha: d.sha.slice(0, 7),
        message: d.message.split("\n")[0].slice(0, 80),
        additions: d.stats.additions,
        deletions: d.stats.deletions,
        filesChanged: d.files.length,
      }));

      const analysisContent = JSON.stringify(
        {
          repoOwner: context.owner,
          repoName: context.repo,
          heuristicAnalysis: analysis,
          commitSample,
          commitDetailSample: detailSample,
          repoMetadata: {
            createdAt: data.metadata.createdAt,
            pushedAt: data.metadata.pushedAt,
            isFork: data.metadata.isFork,
            parentFullName: data.metadata.parentFullName,
            stars: data.metadata.stargazersCount,
            forks: data.metadata.forksCount,
            language: data.metadata.language,
            size: data.metadata.size,
            description: data.metadata.description,
          },
          totalFileCount: context.tree.filter((e) => e.type === "blob").length,
        },
        null,
        2
      );

      const defaultPrompt = `You are a forensic code reviewer for Hack Club's YSWS program. Your job is to analyze git commit history and development patterns to determine if a project represents genuine student development effort.

You have been provided with:
1. A heuristic analysis with red flags, green flags, and a risk score
2. A sample of recent commits with dates and messages
3. Detailed stats for sampled commits (additions/deletions)
4. Repository metadata

Analyze all of this carefully and determine:
- Is this genuine iterative development by a student?
- Or does it look like code was copied/imported/generated and dumped into a repo?
- Are there any patterns that suggest the work wasn't done by the repo owner?

Be nuanced: some legitimate projects are built quickly, and students learning might have messy commit histories. Focus on the most suspicious patterns.

Return JSON:
{
  "verdict": "genuine" | "suspicious" | "likely_copied",
  "confidence": number 0-1,
  "reason": "2-3 sentence explanation",
  "details": ["specific finding 1", "specific finding 2"],
  "recommendations": ["what a human reviewer should look at"]
}`;

      const prompt = (config.prompt as string) || defaultPrompt;
      const aiResult = await this.claude!.askStructured<AIForensicsAnalysis>(
        prompt,
        analysisContent,
        1024
      );

      const evidence = [
        ...analysis.redFlags.map((f) => `RED FLAG: ${f}`),
        ...analysis.greenFlags.map((f) => `OK: ${f}`),
        ...aiResult.details.map((d) => `AI: ${d}`),
        `Heuristic risk score: ${analysis.riskScore}/100`,
        `AI verdict: ${aiResult.verdict} (confidence: ${aiResult.confidence})`,
        ...(aiResult.recommendations.length > 0
          ? [`Recommendations: ${aiResult.recommendations.join("; ")}`]
          : []),
      ];

      let status: "pass" | "fail" | "warning";
      if (aiResult.verdict === "likely_copied") {
        status = "fail";
      } else if (aiResult.verdict === "suspicious") {
        status = "warning";
      } else {
        status = "pass";
      }

      return {
        checkName: this.id,
        required: config.required,
        status:
          config.severity === "warning" && status === "fail"
            ? "warning"
            : status,
        confidence: aiResult.confidence,
        evidence,
        reason: aiResult.reason,
        aiUsed: true,
      };
    } catch {
      // Fall back to heuristic if AI fails
      return this.heuristicResult(analysis, config);
    }
  }
}
